### ISSUE TITLE
nodejs encryptConfigs.js 

### ISSUE THREAD

**Issue by y0d4a** [OWASP/SecureCodingDojo#158]
Hi, i am using docker version and i want to integrate with google oauth.
Problem is that when i enter Google secret and try to run encryptconfig i got an error:

# nodejs encryptConfigs.js 
> ======= config.json ==========
> internal/crypto/hash.js:82
>     throw new ERR_INVALID_ARG_TYPE('data',
>     ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>     at Hash.update (internal/crypto/hash.js:82:11)
>     at getEncParams (/opt/SecureCodingDojo/trainingportal/aescrypto.js:11:48)
>     at Object.exports.encrypt (/opt/SecureCodingDojo/trainingportal/aescrypto.js:27:21)
>     at Object.<anonymous> (/opt/SecureCodingDojo/trainingportal/tools/encryptConfigs.js:19:52)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'ERR_INVALID_ARG_TYPE'
> }

where i am wrong? tnx.

**Comment by y0d4a** [comment]
Ok, i changed script and got encrypted key. 
I entered in config and he is up, but i do not see anywhere google login?
When i try to open callback, i got:

> Error: Unknown authentication strategy "google"
>     at attempt (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:190:39)
>     at authenticate (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
>     at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/node/app/node_modules/express/lib/router/route.js:144:13)
>     at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:114:3)
>     at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
>     at /home/node/app/node_modules/express/lib/router/index.js:284:15
>     at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:346:12)
>     at next (/home/node/app/node_modules/express/lib/router/index.js:280:10)
>     at /home/node/app/node_modules/express-fileupload/lib/index.js:35:14

**Comment by y0d4a** [comment]
it was wrong key in .env :(
now is all fine.
